Add regression test for issue 182
Currently fails with:

    error: future cannot be sent between threads safely
      --> tests/test_macros.rs:51:5
       |
    51 |     require_send_sync(async {
       |     ^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
       |
       = help: the trait `Sync` is not implemented for `core::fmt::Opaque`
    note: future is not `Send` as this value is used across an await
      --> tests/test_macros.rs:56:9
       |
    56 |         future::ready(anyhow!("...")).await;
       |         ^^^^^^^^^^^^^^--------------^^^^^^^- `$crate::private::format_args!($msg)` is later dropped here
       |         |             |
       |         |             has type `[ArgumentV1<'_>; 0]` which is not `Send`
       |         await occurs here, with `$crate::private::format_args!($msg)` maybe used later
    note: required by a bound in `require_send_sync`
      --> tests/test_macros.rs:49:34
       |
    49 |     fn require_send_sync(_: impl Send + Sync) {}
       |                                  ^^^^ required by this bound in `require_send_sync`