Disable backtrace test until converted to provider API
Fails to build starting on nightly-2022-08-03.

    error[E0599]: no method named `backtrace` found for struct `anyhow::Error` in the current scope
      --> tests/test_backtrace.rs:12:19
       |
    12 |     let _ = error.backtrace();
       |                   ^^^^^^^^^ method not found in `anyhow::Error`