Raise rustc required for backtrace feature to 1.67
Required by recent versions of the cc crate.

    error: package `cc v1.0.106` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.65.0
    Either upgrade to rustc 1.67 or newer, or use
    cargo update -p cc@1.0.106 --precise ver
    where `ver` is the latest version of `cc` supporting rustc 1.65.0