Isolate old rustc version tests from needing anyhow dev-dependencies in lockfile
Otherwise:

    error: failed to select a version for the requirement `syn = "^2.0.87"`
    candidate versions found which didn't match: 2.0.56, 2.0.55, 2.0.54, ...
    location searched: crates.io index
    required by package `thiserror-impl v2.0.0`
        ... which satisfies dependency `thiserror-impl = "=2.0.0"` of package `thiserror v2.0.0`
        ... which satisfies dependency `thiserror = "^2"` of package `anyhow v1.0.92`