Disable backtrace build on 1.50
This build step begain failing on a recent update to the `object` crate.

    $ cargo +1.50.0 check --features backtrace
        Updating crates.io index
      Downloaded backtrace v0.3.62
      Downloaded object v0.27.0
    error: failed to parse manifest at `/home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.27.0/Cargo.toml`

    Caused by:
      feature `resolver` is required

      this Cargo does not support nightly features, but if you
      switch to nightly channel you can add
      `cargo-features = ["resolver"]` to enable this feature