Disable backtrace CI on Rust 1.50
The `object` crate doesn't currently work on it.

    $ cargo +1.50.0 check --features backtrace
    warning: unused manifest key: package.rust-version
    error: failed to parse manifest at `/home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.30.0/Cargo.toml`

    Caused by:
      feature `resolver` is required

      this Cargo does not support nightly features, but if you
      switch to nightly channel you can add
      `cargo-features = ["resolver"]` to enable this feature