Add test of unsplit right angle brackets
Currently these aren't being parsed successfully so this fails with:

    ---- test_path stdout ----
    thread 'test_path' panicked at 'assertion failed: `(left == right)`
      left: `"Condition failed: `E::U::<> > E::U::<u8>`"`,
     right: `"Condition failed: `E::U::<> > E::U::<u8>` (U vs U)"`', tests/test_ensure.rs:332:5

    thread 'test_path' panicked at 'assertion failed: `(left == right)`
      left: `"Condition failed: `E::U::<u8> > E::U`"`,
     right: `"Condition failed: `E::U::<u8> > E::U` (U vs U)"`', tests/test_ensure.rs:336:5

    thread 'test_path' panicked at 'assertion failed: `(left == right)`
      left: `"Condition failed: `E::U::<u8> > E::U`"`,
     right: `"Condition failed: `E::U::<u8> > E::U` (U vs U)"`', tests/test_ensure.rs:340:5