Raise minimum rustc for backtrace feature to 1.65
Required by backtrace crate's addr2line dependency.

    error: package `addr2line v0.21.0` cannot be built because it
    requires rustc 1.65 or newer, while the currently active rustc
    version is 1.60.0